### 넘파이 import 하고 , 버전 알아보기

In [1]:
import numpy as np
np.__version__

'1.22.2'

### 1차원 , 2차원 , 3차원 리스트로 배열 만들기

In [6]:
# 1차원 - 한 차원당 하나의 리스트를 넣는다.
a1 = np.array([1, 2, 3, 4, 5])
print(a1)
print(type(a1))
print(a1.shape)


[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


a1의 자료형은 <class 'numpy.ndarray'>를 알 수 있고 , 
a1의 형태는 (5,) , 즉 원소 5개를 가진 1차원 배열임을 알 수 있다.

In [7]:
print(a1[0:5])
a1[0] = 4
a1[0] = 5
a1[0] = 6
print(a1)

[1 2 3 4 5]
[6 2 3 4 5]


넘파이 배열임에도 불구하고, 파이썬 리스트처럼 배열의 원소를 수정할 수 있다.
2차원 배열을 생성해 보자. 

In [9]:
# 2차원 배열을 생성하려면, 큰 배열 안에 1차원 리스트 여러 개를 넣어 생성한다.
a2 = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a2)
print(a2.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [10]:
print(a2[0, 0], a2[1, 1], a2[2, 2])

1 5 9


우리가 사용하는 실제 2차원 행렬처럼 , 행-열 단위로 인덱스 접근하여 조회 가능하다.
3차원 배열을 만들어 보자.

In [14]:
a3 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print(a3)
print(a3.shape)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
(3, 3, 3)


### 배열 생성 및 초기화

우리가 일반적인 행렬 생성처럼 리스트에 값을 담고, 이를 배열처럼 변화시킬 수도 있지만 , <br>
넘파이 함수를 사용하여 값을 초기화할 수도 있다.

- zeros : 모든 요소를 0으로 초기화
- ones : 모든 요소를 1로 초기화

In [16]:
np.zeros(10)
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

- full() : 모든 요소를 지정한 값으로 초기화


In [18]:
np.full((3,3), 1.23)
# 행렬의 형식은 하나의 튜플 안에 넣어야 하고, 값은 튜플 밖에 추가적인 파라미터로 넣어야 한다.

array([[1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23]])

- eye : 단위행렬을 만들어 준다. 단위행렬이기 때문에 정사각행렬 -> 한 변의 길이만 정해주면 된다.
- tri : 삼각행렬을 만들어 준다. 삼각행렬이기 때문에 정사각행렬 -> 한 변의 길이만 정해주면 된다.

In [20]:
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.tri(3)

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

- empty() : 초기화되지 않은 행렬 생성
    - 초기화가 없어서 배열 생성비용 저렴하고 빠르다.
    - 초기화되지 않아서 기존 메모리 위치에 존재하는 값이 있다. -> 매번 실행할 때마다 다르다.

In [22]:
np.empty(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

- _like() : 지정된 배열과 shape가 같은 행렬 작성
    - np.zeros_like()
    - np.ones_like()
    - np.full_like()
    - np.empty_like()
    -> 파라미터에 이전에 배열로 생성한 변수명을 넣으면, 해당 변수와 동일한 형태의 행렬이 작성된다.

In [24]:
print(a1)
np.zeros_like(a1) # a1과 형태가 같은 0으로 초기화된 배열 생성

[6 2 3 4 5]


array([0, 0, 0, 0, 0])

In [25]:
print(a2)
np.zeros_like(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [26]:
print(a3)
np.full_like(a3, 10)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


array([[[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]]])

### 생성한 값으로 배열 생성 

- arange() : 정수 범위로 배열 생성

In [27]:
np.arange(0, 30, 2) # 0부터 30 전까지 step을 2씩 건너뛰며 생성

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

- np.linspace() : 범위 내에서 균등간격으로 로그 스케일로 배열 생성

In [28]:
np.linspace(0, 1, 5 ) # 0부터 1까지의 범위를 균등한 5개의 값으로 나눈다.

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

- np.logspace() : 범위 내에서 균등간격으로 로그 스케일로 배열 생성

In [30]:
np.logspace(0.1, 1, 20)

array([ 1.25892541,  1.40400425,  1.565802  ,  1.74624535,  1.94748304,
        2.1719114 ,  2.42220294,  2.70133812,  3.0126409 ,  3.35981829,
        3.74700446,  4.17881006,  4.66037703,  5.19743987,  5.79639395,
        6.46437163,  7.2093272 ,  8.04013161,  8.9666781 , 10.        ])

### 랜덤값으로 배열 생성

- seed :            난수 발생을 위한 시드(seed) 설정
- permutatioin :    순서를 임의로 바꾸거나 임의의 순열 반환
- shuffle :         리스트나 배열의 순서를 뒤섞음
- random :          랜덤한 수의 배열 생성
- rand :            균등분포에서 표본 추출
- randint :         주어진 최소/최대 범위의 난수 추출
- randn :           표준편차가 1, 평균값 0인 정규분포의 표본 추출
- binomial :        이항분포에서 표본 추출
- beta :            정규분포( 가우시안 )에서 표본 추출
- chisquare :       카이제곱분포에서 표본 추출
- gamma :           감마분포에서 표본 추출
- uniform :         균등( 0 , 1 )에서 표본 추출

- random.random() : 랜덤한 수의 배열 생성

In [31]:
np.random.random((3, 3)) # 값은 랜덤이기 때문에 shape만 정해주면 된다.

array([[0.56090496, 0.09345818, 0.7241498 ],
       [0.4682771 , 0.05661521, 0.25084733],
       [0.5115428 , 0.17981668, 0.30061059]])

- random.randint() : 일정 구간의 랜덤 정수의 배열 생성

In [34]:
np.random.randint(0, 10, (3,3)) 
# 값의 시작점 - 도착점 - 행렬의 형태 순으로 인자 설정

array([[0, 4, 7],
       [6, 0, 5],
       [2, 2, 5]])

- random.normal() : 정규분포( normal distribution )를 고려한 랜덤한 수의 배열 생성
- 평균 = 0 , 표준편차 = 1 , 3 * 3 배열

In [35]:
np.random.normal(0, 1, size=(3, 3))

array([[ 1.27489969,  1.77150969,  1.47169902],
       [ 0.43266239,  0.17645493, -0.19604244],
       [-1.45165211,  0.90948824,  0.01631357]])

- random.rand() : 균등분포를 고려한 랜덤한 수의 배열 생성 

In [36]:
np.random.rand(3, 3)

array([[0.10182291, 0.39981554, 0.54757228],
       [0.79503151, 0.42708623, 0.33756339],
       [0.71920746, 0.11778151, 0.24838798]])

- random.randn() : 표준 정규 분포( standard normal distribution )를 고려한 랜덤한 수의 배열 생성

In [37]:
np.random.randn(3, 3)

array([[-1.1602073 , -0.14785764, -0.87927201],
       [ 0.62409462,  0.05667365,  0.26603149],
       [ 1.11652654,  0.48891172,  0.60092275]])

### 표준 데이터 타입 ( dtype )

여러 배열을 생성하는 함수들에 dype 값을 설정하여 개별적으로 들어가는 원소의 자료형을 정해줄 수 있다.

In [41]:
np.zeros(20, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [42]:
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [43]:
np.full((3, 3), 1.0, dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 날짜/시간 배열 생성

In [46]:
date = np.array('2020-01-01', dtype=np.datetime64)
date

array('2020-01-01', dtype='datetime64[D]')

In [47]:
date + np.arange(12) # 0부터 11일 후까지의 날짜를 모두 출력
# 날짜를 계산 가능한 수로 다룰 수 있다.

array(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
       '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
       '2020-01-09', '2020-01-10', '2020-01-11', '2020-01-12'],
      dtype='datetime64[D]')

In [48]:
datetime = np.datetime64('2020-06-01 12:00')
datetime

numpy.datetime64('2020-06-01T12:00')

In [49]:
datetime = np.datetime64('2020-06-01 12:00:12.34', 'ns')
datetime

numpy.datetime64('2020-06-01T12:00:12.340000000')