In [3]:
import numpy as np

## 배열 조회

### 배열 속성 정보

In [6]:
def array_info(array):
    print(array)
    print('ndim: ', array.ndim)
    print('shape : ', array.shape)
    print('dtype : ', array.dtype)
    print('size : ', array.size)
    print('itemsize : ', array.itemsize)
    print('nbytes : ', array.nbytes) # 전체 원소의 바이트 크기 -> int32형 * 5개 -> 4bytes * 5 = 20
    print('strides: ', array.strides) # 원소 하나의 바이트 크기 -> int32형이면 4바이트

In [5]:
a1 = np.array([1, 2, 3, 4, 5])
array_info(a1)

[1 2 3 4 5]
ndim:  1
shape :  (5,)
dtype :  int32
size :  5
itemsize :  4
nbytes :  20
strides:  (4,)


In [8]:
a2 = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9]])
array_info(a2) 
# strides = (24, 8)
# 하나의 열이 가지고 있는 총 바이트 수 : 24 , 하나의 원소가 가지고 있는 총 바이트 수 : 8

[[1 2 3]
 [4 5 6]
 [7 8 9]]
ndim:  2
shape :  (3, 3)
dtype :  int32
size :  9
itemsize :  4
nbytes :  36
strides:  (12, 4)


In [9]:
a3 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
array_info(a3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
ndim:  3
shape :  (3, 3, 3)
dtype :  int32
size :  27
itemsize :  4
nbytes :  108
strides:  (36, 12, 4)


### 인덱싱

In [10]:
print(a1)
print(a1[0])
print(a1[2])
print(a1[-1]) # 제일 마지막 원소 출력
print(a1[-2]) # 제일 마지막에서 두번째 원소 출력

[1 2 3 4 5]
1
3
5
4


In [11]:
print(a2)
print(a2[0]) # 0번째 행 출력
print(a2[0, 0]) # 0번째 행의 0번째 원소 출력
print(a2[2, -1]) # 2번째 행의 마지막 원소 출력

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
1
9


In [12]:
print(a3)
print(a3[0, 0, 0])
print(a3[1, 1, 1])
print(a3[2, 2, 2])
print(a3[2, 1, -1])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
1
5
9
6


### 슬라이싱(Slicing)

- 슬라이싱 구문 : a[start:stop:step]
- 기본값 : start = 0 , stop = ndim , step = 1

In [13]:
print(a1)
print(a1[0:2]) # 0번째부터 2번째 앞까지
print(a1[:1]) # 1번째 앞까지
print(a1[::2]) 
print(a1[::2]) # 2씩 띄워서
print(a1[::-1]) # 거꾸로 1씩 앞으로

[1 2 3 4 5]
[1 2]
[1]
[1 3 5]
[1 3 5]
[5 4 3 2 1]


In [14]:
print(a2)
print(a2[1]) # 1번째 한 행 출력
print(a2[1, :]) # 1번째 행의 전체 출력
print(a2[:2, :2]) # 0번째와 1번째 행의 각각 0번째, 1번째 항목 출력
print(a2[1:, ::-1]) # 1번째 행부터 출력하는데, 각 항을 거꾸로 출력
print(a2[::-1, ::-1]) # 마지막 행부터 0번째 행까지 거꾸로 출력 , 각 항목도 거꾸로 출력

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
[4 5 6]
[[1 2]
 [4 5]]
[[6 5 4]
 [9 8 7]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


### 불리언 인덱싱( Boolean Indexing )

- 배열 각 요소의 선택 여부를 불리언(True or False)로 지정
- True 값인 인덱스의 값만 조회

In [15]:
print(a1)
bi = [False, True, True, False, True]
print(a1[bi])

[1 2 3 4 5]
[2 3 5]


bi에서 각 인덱스마다 false인 인덱스의 항은 출력하지 않고, <br>
각 인덱스마다 true인 인덱스의 항은 출력한다.

In [18]:
print(a2)
bi = np.random.randint(0, 2, (3,3), dtype=bool)
print(bi)
print(a2[bi])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False False False]
 [ True  True False]
 [False  True  True]]
[4 5 8 9]


### 팬시 인덱싱

In [19]:
print(a1)
print([a1[0], a1[2]])

[1 2 3 4 5]
[1, 3]


In [20]:
ind = [0, 2]
print(a1[ind])

[1 3]


인덱스의 형태에 따라서 결과에 대한 shape이 달라진다.

In [21]:
ind = np.array([[0, 1], [2, 0]])
print(a1[ind])

[[1 2]
 [3 1]]


In [22]:
print(a2)
row = np.array([0, 2])
col = np.array([1, 2])
print(a2[row, col])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 9]


In [23]:
print(a2)
row = np.array([0, 2])
col = np.array([1, 2])
print(a2[row, col])
print(a2[row, :])
print(a2[:, col])
print(a2[row, 1])
print(a2[2, col])
print(a2[row, 1:])
print(a2[1:, col])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 9]
[[1 2 3]
 [7 8 9]]
[[2 3]
 [5 6]
 [8 9]]
[2 8]
[8 9]
[[2 3]
 [8 9]]
[[5 6]
 [8 9]]
