In [1]:
import numpy as np
a1 = np.array([1, 2, 3, 4, 5])
a2 = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9]])
a3 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])

## 배열 값 삽입/수정/삭제/복사

### 배열 값 삽입

- insert() : 배열의 특정 위치에 값 삽입
- axis를 지정하지 않으면 1차원 배열로 변환
- 추가할 방향을 axis로 지정
- 원본 배열 변경없이 새로운 배열 반환

배열의 값을 삽입하는 함수는 사실, 원본 배열의 특정 위치에 값을 삽입한 새로운 배열을 <br>
반환하는 함수이다.

In [7]:
print(a1)
b1 = np.insert(a1, 0, 10)
# 원본배열 - 행의 수 - 열의 수 - 추가할 값 순서로 입력
b1
# 특정 위치에 값을 추가하면, 그 위치부터 기존에 있던 항들은 하나씩 뒤로 밀린다. 

[1 2 3 4 5]


array([10,  1,  2,  3,  4,  5])

In [8]:
c1 = np.insert(a1, 2, 10)
c1

array([ 1,  2, 10,  3,  4,  5])

In [9]:
print(a2)
b2 = np.insert(a2, 1, 10, axis=0)
print(b2)
# 모든 열의 1번째 행에 10을 추가


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [10 10 10]
 [ 4  5  6]
 [ 7  8  9]]


In [10]:
c2 = np.insert(a2, 1, 10, axis=1)
print(c2)
# 모든 행의 1번째 열에 10을 추가

[[ 1 10  2  3]
 [ 4 10  5  6]
 [ 7 10  8  9]]


### 배열 수정

- 배열의 인덱싱으로 접근하여 값 수정

In [11]:
print(a1)
a1[0] = 4
a1[1] = 5
a1[2] = 6
print(a1)

[1 2 3 4 5]
[1 2 3 4 5]


In [15]:
a1[:1] = 9
print(a1)

i = np.array([1, 3, 4])
a1[ i ] = 0 # fancy indexing
print(a1)
a1[ i ] += 4
print(a1)

[9 0 3 0 0]
[9 0 3 0 0]
[9 4 3 4 4]


In [16]:
print(a2)
a2[0, 0] = 1
a2[1, 1] = 2
a2[2, 2] = 3
a2[0] = 1 # 0번째 행을 전부 1로 변경
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 1 1]
 [4 2 6]
 [7 8 3]]


In [17]:
a2[1:, :2] = 9
print(a2)
row = np.array([0, 1])
col = np.array([1, 2])
a2[row, col] = 0
print(a2)

[[1 1 1]
 [9 9 6]
 [9 9 3]]
[[1 0 1]
 [9 9 0]
 [9 9 3]]


### 배열 값 삭제

- delete() : 배열의 특정 위치에 값 삭제
- axis를 저장하지 않으면 1차원 배열로 반환
- 삭제할 방향을 axis로 지정
- 원본 배열 변경없이 새로운 배열 반환

In [18]:
print(a1)
b1 = np.delete(a1, 1) # 1번째 인덱스 값을 삭제하고, 뒤에 있던 값을 당겨 온다.
print(b1)
print(a1) # 원본 값은 바뀌지 않았다.

[9 4 3 4 4]
[9 3 4 4]


In [19]:
print(a2)
b2 = np.delete(a2, 1, axis=0) # 1번째 행(axis=0)을 삭제한다. 그 다음 항부터는 당겨온다. 
print(b2)

[[1 0 1]
 [9 9 0]
 [9 9 3]]
[[1 0 1]
 [9 9 3]]


In [20]:
c2 = np.delete(a2, 1, axis=1) # 1번째 열(axis = 1)을 삭제한다. 그 다음 항부터는 당겨온다.
print(c2)

[[1 1]
 [9 0]
 [9 3]]


### 배열 복사

- 리스트 자료형과 달리 배열의 슬라이스는 복사본이 아니다.

In [21]:
print(a2)
print(a2[:2, :2])
a2_sub = a2[:2, :2]
print(a2_sub)      # 원본에서 0번째~1번째 행의 0번째~1번째 열의 값을 슬라이싱하여 가져왔다.
a2_sub[:, 1] = 0   # a2_sub의 전체 1번째 열의 값을 0으로 수정
print(a2_sub)      # 수정된 값 출력
print(a2)          # 원본 출력 

[[1 0 1]
 [9 9 0]
 [9 9 3]]
[[1 0]
 [9 9]]
[[1 0]
 [9 9]]
[[1 0]
 [9 0]]
[[1 0 1]
 [9 0 0]
 [9 9 3]]


맨 처음 출력한 원본과, 작업 후에 원본의 출력값이 다르다. <br>
복사할 때는 레퍼런스 단위로 접근한다. 따라서 해당 주소의 값을 변경하면 정말로 원본도 바뀐다.
내가 복사를 하고 싶다면 -> 명시적으로 copy()라는 함수를 사용해야 한다.

- copy() : 배열이나 하위 배열 내의 값을 명시적으로 복사

In [23]:
print(a2)
a2_sub_copy = a2[:2, :2].copy()
print(a2_sub_copy)
a2_sub_copy[:, 1] = 1
print(a2_sub_copy)
print(a2)


[[1 0 1]
 [9 0 0]
 [9 9 3]]
[[1 0]
 [9 0]]
[[1 1]
 [9 1]]
[[1 0 1]
 [9 0 0]
 [9 9 3]]


배열의 값을 아예 새로운 메모리에 할당하였기 때문에 , <br>
새로운 값을 수정하더라도, 원본의 메모리에 담긴 값에 영향을 미치지 않는다.