In [1]:
import numpy as np
a1 = np.array([1, 2, 3, 4, 5])
a2 = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9]])
a3 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])

## 배열 변환

### 배열 전치 및 축 변경

In [2]:
print(a2)
print(a2.T) # .T 키워드로 전치된 배열을 볼 수 있다.

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [3]:
print(a3)
print(a3.T)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 1 1]
  [4 4 4]
  [7 7 7]]

 [[2 2 2]
  [5 5 5]
  [8 8 8]]

 [[3 3 3]
  [6 6 6]
  [9 9 9]]]


In [4]:
print(a2)
print(a2.swapaxes(1, 0)) # 1번째 축과 0번째 축을 바꾼다.

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [6]:
print(a3)
print(a3.swapaxes(0, 1))


[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[4 5 6]
  [4 5 6]
  [4 5 6]]

 [[7 8 9]
  [7 8 9]
  [7 8 9]]]


In [7]:
print(a3.swapaxes(1, 2))

[[[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]]


### 배열 재구조화

- reshape() : 배열의 형상을 변경

In [9]:
n1 = np.arange(1, 10)
print(n1)
print(n1.reshape(3, 3))

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


- newaxis() : 새로운 축 추가

In [10]:
print(n1)
print(n1[np.newaxis, :5]) # 0부터 4번째 원소까지의 항을 행 방향으로 출력한다.
print(n1[:5, np.newaxis]) # 0부터 4번째 원소까지의 항을 열 방향으로 출력한다.

[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


### 배열 크기 변경

- 배열 모양만 변경

In [20]:
n2 = np.random.randint(0, 10, (2, 5))
print(n2)

[[5 4 5 3 9]
 [8 4 0 1 9]]


In [21]:
n2.resize((5, 2))
print(n2)

[[5 4]
 [5 3]
 [9 8]
 [4 0]
 [1 9]]


- 배열 크기 증가
- 남는 공간은 0으로 채워짐

In [22]:
n2.resize((5, 5))
print(n2)

[[5 4 5 3 9]
 [8 4 0 1 9]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


- 배열 크기 감소
- 포함되지 않은 값은 삭제됨

In [23]:
n2.resize((3, 3))
print(n2)

[[5 4 5]
 [3 9 8]
 [4 0 1]]


### 배열 추가

- append( ) : 배열의 끝에 값 추가

In [25]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
b2 = np.arange(10, 19).reshape(3, 3)
print(b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


- axis 지정이 없으면 1차원 형태로 변형되어 결합

In [26]:
c2 = np.append(a2, b2)
print(c2) # 축 지정이 없기 때문에 1차원 형태로 단순하게 값을 추가한다.

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


- axis를 0으로 지정
- shape[ 0 ]을 제외한 나머지 shape은 같아야 한다.
- ( 행의 개수를 제외하고 , 나머지 열의 개수는 같아야 한다. 그래야 추가가 가능하다. )

In [27]:
c2 = np.append(a2, b2, axis=0) # 행 단위로 붙이기
print(c2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


- axis를 1로 지정
- shape[1]을 제외한 나머지 shape은 같아야 한다.

In [28]:
c2 = np.append(a2, b2, axis=1) # 열 단위로 붙인다.
print(c2)

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


### 배열 연결

- concatenate() : 튜플이나 배열의 리스트를 인수로 사용해 배열 연결

In [29]:
a1 = np.array([1, 3, 5])
b1 = np.array([2, 4, 6])
np.concatenate([a1, b1])

array([1, 3, 5, 2, 4, 6])

In [30]:
c1 = np.array([7, 8, 9])
np.concatenate([a1, b1, c1])

array([1, 3, 5, 2, 4, 6, 7, 8, 9])

In [31]:
a2 = np.array([[1, 2, 3],
               [4, 5, 6]])
np.concatenate([a2, a2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

밑에 붙는 것을 알 수 있다. axis의 디폴트 값이 0이기 때문이다.

In [32]:
a2 = np.array([[1, 2, 3],
               [4, 5, 6]])
np.concatenate([a2, a2], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

- np.vstack() : 수직 스택(vertial stack), 1차원으로 연결

In [33]:
np.vstack([a2, b2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

hstack() : 수평 스택( horizontal stack ) , 2차원으로 연결

In [34]:
np.hstack([a2, a2])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

- dstack() : 깊이 스택(depth stack), 3차원으로 연결

In [35]:
np.dstack([a2, a2])

array([[[1, 1],
        [2, 2],
        [3, 3]],

       [[4, 4],
        [5, 5],
        [6, 6]]])

나온 결과가 조금 이상하다. <br>
세로로 하나씩 붙은 다음에, 2*3*2의 형식으로 붙었다고 보면 된다.

- np.stack() : 새로운 차원으로 연결

In [36]:
np.stack([a2, a2]) # 새로운 행렬이 바로 뒤의 행렬로 추가되었다고 보면 된다. 

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

### 배열 분할

- split() : 배열 분할

In [38]:
a1 = np.arange(1, 10)
print(a1)
b1, c1 = np.split(a1, [5]) # 인덱스 기반으로 split된다.
print(b1, c1)
b1, c1, d1, e1, f1 = np.split(a1, [2, 4, 6, 8])
print(b1, c1, d1, e1, f1)

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5] [6 7 8 9]
[1 2] [3 4] [5 6] [7 8] [9]


- vsplit() : 수직 분할 , 1차원으로 분할

In [39]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
b2, c2 = np.vsplit(a2, [2]) # 2번째 행을 기준으로 나눈다. : 0~1번째 <-> 2번째~
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
[[7 8 9]]


- hsplit() : 수평 분할 , 2차원으로 분할

In [43]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
b2, c2 = np.hsplit(a2, [2]) # 2번째 열을 기준으로 나눈다. : 0~1번째 <-> 2번째~
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]
 [7 8]]
[[3]
 [6]
 [9]]


- dsplit() : 깊이 분할 , 3차원으로 분할

In [46]:
a3 = np.arange(1, 28).reshape(3, 3, 3)
print(a3)
b3, c3 = np.dsplit(a3, [2]) # 모든 페이지의 2번째 열부터 자른다.
print(b3)


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[[[ 1  2]
  [ 4  5]
  [ 7  8]]

 [[10 11]
  [13 14]
  [16 17]]

 [[19 20]
  [22 23]
  [25 26]]]


In [48]:
print(c3)

[[[ 3]
  [ 6]
  [ 9]]

 [[12]
  [15]
  [18]]

 [[21]
  [24]
  [27]]]


- 