In [1]:
import numpy as np

### 집계 함수( Aggergate Functions )

집계 함수에는 NaN 안전 모드를 위한 별도의 함수가 있다. <br>
일반 집계 함수의 이름 앞에 nan을 붙이면 된다<br>
예시 ) np.sum => np.nansum

집계 함수는 숫자에 대해서만 할 수 있다. 그런데 숫자가 아닌 값을 더하게 되더라도 <br>
nan 안전 모드 함수를 사용하면, 에러를 발생하지 않고, 안전하게 수행한다.

일반 집계 함수에 대응하는 NaN 안전 모드 함수가 존재하는 경우가 있고, 아닌 경우가 있다.

- np.sum() : 합 계산

In [ ]:
a2 = np.random.randint(1, 10, size=(3,3))
print(a2)
print(a2.sum(), np.sum(a2))
print(a2.sum(axis=0), np.sum(a2, axis=0)) # 세로로 더하기
print(a2.sum(axis=1), np.sum(a2, axis=1)) # 가로로 더하기

[[7 3 6]
 [8 8 3]
 [9 5 5]]
54 54
[24 16 14] [24 16 14]
[16 19 19] [16 19 19]


- np.cumsum() : 누적합 계산

In [ ]:
print(a2)
print(a2.cumsum())
print(a2.cumsum(axis=0)) # 세로로 누적합
print(a2.cumsum(axis=1)) # 가로로 누적합

[[7 3 6]
 [8 8 3]
 [9 5 5]]
[ 7 10 16 24 32 35 44 49 54]
[[ 7  3  6]
 [15 11  9]
 [24 16 14]]
[[ 7 10 16]
 [ 8 16 19]
 [ 9 14 19]]


- diff() : 차분 계산

In [ ]:
print(a2)
print(np.diff(a2))
print(np.diff(a2, axis=0)) # 세로로
print(np.diff(a2, axis=1)) # 가로로 

[[7 3 6]
 [8 8 3]
 [9 5 5]]
[[-4  3]
 [ 0 -5]
 [-4  0]]
[[ 1  5 -3]
 [ 1 -3  2]]
[[-4  3]
 [ 0 -5]
 [-4  0]]


- prod() : 곱 계산

In [ ]:
print(a2)
print(np.prod(a2))
print(np.prod(a2, axis=0))
print(np.prod(a2, axis=1))

[[7 3 6]
 [8 8 3]
 [9 5 5]]
5443200
[504 120  90]
[126 192 225]


- cumprod() : 누적곱 계산

In [ ]:
print(a2)
print(np.cumprod(a2))
print(np.cumprod(a2, axis = 0))
print(np.cumprod(a2, axis = 1))

[[7 3 6]
 [8 8 3]
 [9 5 5]]
[      7      21     126    1008    8064   24192  217728 1088640 5443200]
[[  7   3   6]
 [ 56  24  18]
 [504 120  90]]
[[  7  21 126]
 [  8  64 192]
 [  9  45 225]]


- dot() / matmul() : 점곱 / 행렬곱 계산

In [ ]:
print(a2)
b2 = np.ones_like(a2)
print(b2)
print(np.dot(a2, b2))
print(np.matmul(a2, b2))

[[7 3 6]
 [8 8 3]
 [9 5 5]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[16 16 16]
 [19 19 19]
 [19 19 19]]
[[16 16 16]
 [19 19 19]
 [19 19 19]]


tensordot() : 텐서곱 계산

In [ ]:
print(a2)
print(b2)

[[7 3 6]
 [8 8 3]
 [9 5 5]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
print(np.tensordot(a2, b2)) # a1과 b1의 원소를 각각 모두 곱한 것을 더한 결과

54


In [ ]:
print(np.tensordot(a2, b2, axes=0))

[[[[7 7 7]
   [7 7 7]
   [7 7 7]]

  [[3 3 3]
   [3 3 3]
   [3 3 3]]

  [[6 6 6]
   [6 6 6]
   [6 6 6]]]


 [[[8 8 8]
   [8 8 8]
   [8 8 8]]

  [[8 8 8]
   [8 8 8]
   [8 8 8]]

  [[3 3 3]
   [3 3 3]
   [3 3 3]]]


 [[[9 9 9]
   [9 9 9]
   [9 9 9]]

  [[5 5 5]
   [5 5 5]
   [5 5 5]]

  [[5 5 5]
   [5 5 5]
   [5 5 5]]]]


In [ ]:
print(np.tensordot(a2, b2, axes=1))

[[16 16 16]
 [19 19 19]
 [19 19 19]]


- np.cross() : 벡터곱

In [ ]:
x = [1, 2, 3]
y = [4, 5, 6]
print(np.cross(x, y))

[-3  6 -3]


- inner() : 내적
- outer() : 외적

In [ ]:
print(a2)
print(b2)
print(np.inner(a2, b2)) # dot product 와 동일한 결고
print(np.outer(a2, b2))

[[7 3 6]
 [8 8 3]
 [9 5 5]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[16 16 16]
 [19 19 19]
 [19 19 19]]
[[7 7 7 7 7 7 7 7 7]
 [3 3 3 3 3 3 3 3 3]
 [6 6 6 6 6 6 6 6 6]
 [8 8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8 8]
 [3 3 3 3 3 3 3 3 3]
 [9 9 9 9 9 9 9 9 9]
 [5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5]]


- mean() : 평균 계산

In [ ]:
print(a2)
print(np.mean(a2))
print(np.mean(a2, axis=0))
print(np.mean(a2, axis=1))

[[7 3 6]
 [8 8 3]
 [9 5 5]]
6.0
[8.         5.33333333 4.66666667]
[5.33333333 6.33333333 6.33333333]


- std() : 표준편차 계산

In [ ]:
print(a2)
print(np.std(a2))
print(np.std(a2, axis=0))
print(np.std(a2, axis=1))

[[7 3 6]
 [8 8 3]
 [9 5 5]]
2.0548046676563256
[0.81649658 2.05480467 1.24721913]
[1.69967317 2.3570226  1.88561808]


- var() : 분산 계산

In [ ]:
print(a2)
print(np.var(a2))
print(np.var(a2, axis=0))
print(np.var(a2, axis=1))

[[7 3 6]
 [8 8 3]
 [9 5 5]]
4.222222222222222
[0.66666667 4.22222222 1.55555556]
[2.88888889 5.55555556 3.55555556]


- min() : 최소값

In [ ]:
print(a2)
print(np.min(a2))
print(np.min(a2, axis=0))
print(np.min(a2, axis=1))

[[7 3 6]
 [8 8 3]
 [9 5 5]]
3
[7 3 3]
[3 3 5]


- max() : 최대값

In [ ]:
print(a2)
print(np.max(a2))
print(np.max(a2, axis=0))
print(np.max(a2, axis=1))

[[7 3 6]
 [8 8 3]
 [9 5 5]]
9
[9 8 6]
[7 8 9]


- argmin() : 최소값 인덱스

In [ ]:
print(a2)
print(np.argmin(a2))
print(np.argmin(a2, axis=0))
print(np.argmin(a2, axis=1))

[[7 3 6]
 [8 8 3]
 [9 5 5]]
1
[0 0 1]
[1 2 1]


- median() : 중앙값

In [ ]:
print(a2)
print(np.median(a2))
print(np.median(a2, axis=0))
print(np.median(a2, axis=1))

[[7 3 6]
 [8 8 3]
 [9 5 5]]
6.0
[8. 5. 5.]
[6. 8. 5.]


- percentile() : 백분위 수

In [ ]:
a1 = np.array([0, 1, 2, 3])
print(a1)
print(np.percentile(a1, [0, 20, 40, 60, 80, 100], interpolation='linear'))
print(np.percentile(a1, [0, 20, 40, 60, 80, 100], interpolation='higher'))
print(np.percentile(a1, [0, 20, 40, 60, 80, 100], interpolation='lower'))
print(np.percentile(a1, [0, 20, 40, 60, 80, 100], interpolation='nearest'))
print(np.percentile(a1, [0, 20, 40, 60, 80, 100], interpolation='midpoint'))

[0 1 2 3]
[0.  0.6 1.2 1.8 2.4 3. ]
[0 1 2 2 3 3]
[0 0 1 1 2 3]
[0 1 1 2 2 3]
[0.  0.5 1.5 1.5 2.5 3. ]


C:\Users\com\AppData\Local\Temp/ipykernel_10668/3364568261.py:3: DeprecationWarning: the `interpolation=` argument to percentile was renamed to `method=`, which has additional options.
Users of the modes 'nearest', 'lower', 'higher', or 'midpoint' are encouraged to review the method they. (Deprecated NumPy 1.22)
  print(np.percentile(a1, [0, 20, 40, 60, 80, 100], interpolation='linear'))
C:\Users\com\AppData\Local\Temp/ipykernel_10668/3364568261.py:4: DeprecationWarning: the `interpolation=` argument to percentile was renamed to `method=`, which has additional options.
Users of the modes 'nearest', 'lower', 'higher', or 'midpoint' are encouraged to review the method they. (Deprecated NumPy 1.22)
  print(np.percentile(a1, [0, 20, 40, 60, 80, 100], interpolation='higher'))
C:\Users\com\AppData\Local\Temp/ipykernel_10668/3364568261.py:5: DeprecationWarning: the `interpolation=` argument to percentile was renamed to `method=`, which has additional options.
Users of the modes 'nearest', 'lo

- any() 

In [ ]:
a2 = np.array([[False, False, False],
               [False, True, True],
               [False, True, True]])
print(a2) 
print(np.any(a2)) # 각 원소 중에서 하나라도 True이면 True
print(np.any(a2, axis=0))
print(np.any(a2, axis=1))

[[False False False]
 [False  True  True]
 [False  True  True]]
True
[False  True  True]
[False  True  True]


- all()

In [ ]:
a2 = np.array([[False, False, True],
               [True, True, True],
               [False, True, True]])
print(a2) 
print(np.all(a2)) # 각 원소 중에서 하나라도 False이면 False
print(np.all(a2, axis=0))
print(np.all(a2, axis=1))

[[False False  True]
 [ True  True  True]
 [False  True  True]]
False
[False False  True]
[False  True False]
