# 1-1 : N차원 배열 생성하기

### 가장 일반적인 넘파이 배열 생성하기

NumPy 배열 생성 함수 : `np.array(배열)`

In [1]:
# 패키지를 import 먼저 해야 넘파이 패키지 쓸 수 있음
import numpy as np

# 1차원 배열
arr1 = np.array([1, 2, 3])
print(arr1)

[1 2 3]


In [3]:
# 2차원 배열
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


numpy 배열과 일반 리스트는 성격이 다르다.

In [6]:
# 일반 리스트의 값과 데이터형 
print([1, 2, 3])
print(type([1, 2, 3]))

# 넘파이 배열의 값과 데이터형
print(arr1)
print(arr1.dtype)

[1, 2, 3]
<class 'list'>
[1 2 3]
int32


### 리스트나 튜플로 n차원 배열 만들기

In [8]:
# 튜플을 넘파이 배열로 변환하기
tpl = (4, 5, 6)
arr = np.array(tpl)
print(arr)

[4 5 6]


In [10]:
# 리스트를 넘파일 배열로 변환하기
lst = [1, 2, 3]
arr = np.array(lst)
print(arr)

[1 2 3]


In [11]:
# 2차원 리스트를 2차원 넘파이 배열로 변환하기
lst2 = [[1, 2, 3], [4, 5, 6]]
arr2 = np.array(lst2)
print(arr2)

[[1 2 3]
 [4 5 6]]


배열의 행과 열의 모양을 알려 주는 ***속성***은 `shape` 이다.

In [13]:
#shape
arr1 = np.array([1, 2, 3])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

print(arr1.shape, arr2.shape)

(3,) (2, 3)


arr1은 3 형태의 배열(1차원 배열) , arr2는 2 * 3 형태의 2차원 배열임을 알려준다.

차원을 알려주는 속성은 `ndim`이다.

In [14]:
# ndim
print(arr1.ndim, arr2.ndim)

1 2


arr1은 1차원, arr2는 2차원임을 알려준다.

배열의 크기를 알려주는 속성은 `size`이다.

In [15]:
# size
print(arr1.size, arr2.size)

3 6


arr1의 원소 개수는 3개, arr2의 원소 개수는 6개임을 알려준다.